name: validate-markdown

on: [push, pull_request]

jobs:
  mdv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Validate markdown
      run: npx mdv versions/*.md
